# Make sure the metric prefix ends with a |
#This will create this metric in all the tiers, under this path.
#metricPrefix: "Custom Metrics|SQL|"
#This will create it in specific Tier. Replace <ComponentID> with TierID
metricPrefix: "Server|Component:<ComponentID>|Custom Metrics|SQL|"


dbServers:
    - displayName: "DCCIH-DB-test"
      connectionUrl: "jdbc:oracle:thin:@localhost:1521/orcl"
      driver: "oracle.jdbc.driver.OracleDriver"

      connectionProperties:
          user: "SYSTEM"
          password: "admin"
     #     encryptedPassword: ""  #Needs to be used in conjunction with `encryptionKey`. Please read the extension documentation to generate encrypted password. https://community.appdynamics.com/t5/Knowledge-Base/How-do-I-use-Password-Encryption-with-Extensions/ta-p/29397
      analyticsEventPublishApi:
          url: "https://fra-ana-api.saas.appdynamics.com/events/publish/dccih_commissioning_transactions"
          controllerGlobalAccountName: "centricapreprod_65f907d1-1478-4a78-b8e1-0b91a3ae2707"
          eventsAPIKey: "2522bdd9-e5ec-43b2-88c8-00644f3a1d4c"

      queries:
        - displayName: "Query test 1"
          queryStmt: "select col1,col2,col3,col4,col1,col2,col3,col4 from test WHERE col3=22"
          columns:
            - name: "col1"
              analyticsColName: "BS_TRANSACTION_ID"

            - name: "col2"
              analyticsColName: "BS_ID"

            - name: "col3"
              analyticsColName: "TIME_IN_SECS"

            - name: "col4"
              analyticsColName: "TRANS_STATUS_ID"

            - name: "col1"
              analyticsColName: "START_DATETIME"

            - name: "col2"
              analyticsColName: "STOP_DATETIME"

            - name: "col3"
              analyticsColName: "ERROR_CODE"

            - name: "col4"
              analyticsColName: "TARGET_ID"

        - displayName: "Query test 2"
          queryStmt: "SELECT column1,column2,column3,column4,column5,column6,column7,column8 FROM test2 where column4=12"
          columns:
            - name: "column1"
              analyticsColName: "BS_TRANSACTION_ID"

            - name: "column2"
              analyticsColName: "BS_ID"

            - name: "column3"
              analyticsColName: "TIME_IN_SECS"

            - name: "column4"
              analyticsColName: "TRANS_STATUS_ID"

            - name: "column5"
              analyticsColName: "START_DATETIME"

            - name: "column6"
              analyticsColName: "STOP_DATETIME"

            - name: "column7"
              analyticsColName: "ERROR_CODE"

            - name: "column8"
              analyticsColName: "TARGET_ID"

        # - displayName: "TRANSACTION DATABASE"
        #   queryStmt: "SELECT TARGET_BOX, REACH_DURATION, ROUTER_DURATION FROM ASG_TRANSACTIONS WHERE TARGET_BOX IN ('target1','target2','target3','target4','target5')"
        #   columns:
        #     - name: "TARGET_BOX"
        #       type: "metricPathName"

        #     - name: "REACH_DURATION"
        #       type: "metricValue"

        #     - name: "ROUTER_DURATION"
        #       type: "metricValue"

        # - displayName: "Node Status"
        #   queryStmt: "Select NODE_NAME, NODE_STATE from NODE_STATES"
        #   columns:
        #     - name: "NODE_NAME"
        #       type: "metricPathName"

        #     - name: "NODE_STATE"
        #       type: "metricValue"
        #       properties:
        #         convert:
        #           "INITIALIZING" : 0
        #           "UP" : 1
        #           "DOWN" : 2
        #           "READY" : 3
        #           "UNSAFE" : 4
        #           "SHUTDOWN" : 5
        #           "RECOVERING" : 6

      # Replaces characters in metric name with the specified characters.
      # "replace" takes any regular expression
      # "replaceWith" takes the string to replace the matched characters

      metricCharacterReplacer:
        - replace: "%"
          replaceWith: ""
        - replace: ","
          replaceWith: "-"


numberOfThreads: 5

#Run it as a scheduled task instead of running every minute.
#Configure it. refer: https://community.appdynamics.com/t5/Knowledge-Base/Task-Schedule-for-Extensions/ta-p/35414#Configuration
#taskSchedule:
  #numberOfThreads: 1
  #taskDelaySeconds: 120


controllerInfo:
  controllerHost: "controller"
  controllerPort: 8090
  account: "customer1"
  username: "admin"
  password: "admin"
  encryptedPassword: ""
  controllerSslEnabled: false
  enableOrchestration: false
  uniqueHostId: ""
  accountAccessKey: ""
  machinePath: ""
  simEnabled: true
  applicationName: ""
  tierName: ""
  nodeName: ""

encryptionKey: "abcd"


